import {
  LayoutDashboard,
  Users,
  Building2,
  Briefcase,
  CalendarClock,
  Banknote,
  Settings,
  User,
  FileText,
  Handshake,
  CreditCard,
  Receipt,
  LayoutGrid,
  ScrollText,
  Activity,
  ShieldCheck,
  Clock,
  FolderOpen,
  BarChart3,
  ReceiptText,
  Bell,
} from 'lucide-react'

import avatar1 from '../assets/avatar1.png'
import avatar2 from '../assets/avatar2.png'
import avatar3 from '../assets/avatar3.png'

export const ROLES = {
  admin: {
    label: 'Admin',
    basePath: '/admin',
    user: { name: 'Alex Rivera', role: 'Super Admin', avatar: avatar1 },
    nav: [
      { label: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
      { label: 'Tenants', path: '/admin/tenants', icon: Building2 },
      { label: 'Partners', path: '/admin/partners', icon: Handshake },
      { label: 'Subscriptions', path: '/admin/subscriptions', icon: CreditCard },
      { label: 'Billing', path: '/admin/billing', icon: Receipt },
      { label: 'Marketplace', path: '/admin/marketplace', icon: LayoutGrid },
      { label: 'Users', path: '/admin/users', icon: Users },
      { label: 'Employers', path: '/admin/employers', icon: Briefcase },
      { label: 'Leave', path: '/admin/leave', icon: CalendarClock },
      { label: 'Audit Logs', path: '/admin/audit-logs', icon: ScrollText },
      { label: 'Monitoring', path: '/admin/monitoring', icon: Activity },
      { label: 'Security', path: '/admin/security', icon: ShieldCheck },
      { label: 'Settings', path: '/admin/settings', icon: Settings },
    ],
  },
  employer: {
    label: 'Employer',
    basePath: '/employer',
    user: { name: 'Sarah Chen', role: 'HR Manager', avatar: avatar2 },
    nav: [
      { label: 'Dashboard', path: '/employer/dashboard', icon: LayoutDashboard },
      { label: 'Employees', path: '/employer/employees', icon: Users },
      { label: 'Time Tracking', path: '/employer/time-tracking', icon: Clock },
      { label: 'Leave', path: '/employer/leave', icon: CalendarClock },
      { label: 'Payroll', path: '/employer/payroll', icon: Banknote },
      { label: 'Documents', path: '/employer/documents', icon: FolderOpen },
      { label: 'Reports', path: '/employer/reports', icon: BarChart3 },
      { label: 'Settings', path: '/employer/settings', icon: Settings },
    ],
  },
  employee: {
    label: 'Employee',
    basePath: '/employee',
    user: { name: 'Sarah Miller', role: 'Product Designer', avatar: avatar3 },
    nav: [
      { label: 'Dashboard', path: '/employee/dashboard', icon: LayoutDashboard },
      { label: 'Profile', path: '/employee/profile', icon: User },
      { label: 'Time Tracking', path: '/employee/time-tracking', icon: Clock },
      { label: 'Leave', path: '/employee/leave', icon: CalendarClock },
      { label: 'Payslips', path: '/employee/payslips', icon: FileText },
      { label: 'Tax Forms', path: '/employee/tax-forms', icon: ReceiptText },
      { label: 'Documents', path: '/employee/documents', icon: FolderOpen },
      { label: 'Notifications', path: '/employee/notifications', icon: Bell },
      { label: 'Settings', path: '/employee/settings', icon: Settings },
    ],
  },
}
